#!/bin/sh
#
#  dosdiff FILENAME [--options-to-diff]
#

base=${1%.*}
suf=${1#*.}
if [ "$base" = "$1" ]; then
  dosname=$(echo $base | cut -c1-8)
else
  dosname=$(echo $base | cut -c1-8).$suf
fi
dosname=`echo $dosname | tr A-Z a-z`

diff $2 --ignore-space-change -u $1 /dos/p/vplanets/cc/tputuner/$dosname
