#!/bin/sh
# faßt die Ausgaben von tputuner zusammen:
#  tputuner unit1.tpu >liste
#  tputuner unit2.tpu >>liste
#  tputuner unit3.tpu >>liste
#  summarize liste
awk '
  BEGIN {o=0;oc=0;n=0;nc=0}
  $1 ~ /Original/ {o+=$3;oc+=$5}
  $4 ~ /header:/ {n+=$5;nc+=$7}
  END {print "Original size: ",o," (Code: ",oc,")";
       print "New size:      ",n," (Code: ",nc,")";
       print "Saved:         ",o-n," (Code: ",oc-nc,")"}' <$1

